spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/helios
spring.datasource.username=postgres
spring.datasource.password=${DB_PASS}

spring.kafka.bootstrap-servers=kafka:9092

helios.etcd.endpoint=http://etcd:2379
helios.instance.id=${INSTANCE_ID}