spring.application.name=helios

spring.datasource.url=jdbc:postgresql://localhost:5432/helios
spring.datasource.username=postgres
spring.datasource.password=${DB_PASS}


logging.level.root=WARN


spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate